MINGWDIR=/mingw

CC = gcc
LINKER = $(CC)
BINARY=hcc.exe
DESTDIR=../bin
CFLAGS = -I$(MINGWDIR)/include -O2 -Wall
LDFLAGS = -mconsole
LDLIBS= 

all : $(BINARY)

clean : 
	rm -f *.o core

# Rules for turning source files into .o files
%.o: %.c
	$(CC) -c $(CFLAGS) -o $@ $<


HCCOBJS= cmdlib.o \
	expr.o \
	hcc.o \
	pr_comp.o \
	pr_lex.o \
	stmt.o

$(BINARY) : $(HCCOBJS)
	$(LINKER) -o $(DESTDIR)/$(BINARY) $(HCCOBJS) $(LDFLAGS) $(LDLIBS)
