// quakedef.h -- primary header for client

#define	QUAKE_GAME			// as opposed to utilities

#define HOT_VERSION_MAJ 1
#define HOT_VERSION_MID 2
#define HOT_VERSION_MIN 3
#ifdef PLATFORM_UNIX
#define VERSION_PLATFORM "Linux"
#else
#define VERSION_PLATFORM "Windows"
#endif

//define	PARANOID			// speed sapping error checking

#define AOT_USERDIR ".aot/hw"

#include <math.h>
#include <string.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <setjmp.h>

#include "bothdefs.h"

#include "common.h"
#include "bspfile.h"
#include "vid.h"
#include "sys.h"
#include "zone.h"
#include "mathlib.h"
#include "wad.h"
#include "draw.h"
#include "cvar.h"
#include "screen.h"
#include "net.h"
#include "protocol.h"
#include "cmd.h"
#ifdef PLATFORM_UNIX
#include "../Server/pr_comp.h"
#include "../Server/progdefs.h"
#else
#include "..\server\pr_comp.h"			// defs shared with qcc
#include "..\server\progdefs.h"			// generated by program cdefs
#endif
#include "strings.h"
#include "sbar.h"
#include "sound.h"
#include "mididef.h"
#include "render.h"
#include "cl_effect.h"
#include "client.h"

#ifdef GLQUAKE
#include "gl_model.h"
#else
#include "model.h"
#include "d_iface.h"
#endif

#include "input.h"
#include "keys.h"
#include "console.h"
#include "view.h"
#include "menu.h"
#include "crc.h"
#include "cdaudio.h"
#include "pmove.h"
#include "mididef.h"

#ifdef GLQUAKE
#include "glquake.h"
#endif

//=============================================================================

// the host system specifies the base of the directory tree, the
// command line parms passed to the program, and the amount of memory
// available for the program to use

typedef struct
{
	char	*basedir;
        char    *userdir;
	char	*cachedir;		// for development over ISDN lines
	int		argc;
	char	**argv;
	void	*membase;
	int		memsize;
} quakeparms_t;


//=============================================================================

#define MAX_NUM_ARGVS	50


extern qboolean noclip_anglehack;


//
// host
//
extern	quakeparms_t host_parms;

extern	cvar_t		sys_ticrate;
extern	cvar_t		sys_nostdout;
extern	cvar_t		developer;

extern	cvar_t	password;
extern	cvar_t  talksounds;

extern	qboolean	host_initialized;		// true if into command execution
extern	double		host_frametime;
extern	byte		*host_basepal;
extern	byte		*host_colormap;
extern	int			host_framecount;	// incremented every frame, never reset
extern	double		realtime;			// not bounded in any way, changed at
										// start of every frame, never reset

void Host_ServerFrame (void);
void Host_InitCommands (void);
void Host_Init (quakeparms_t *parms);
void Host_Shutdown(void);
void Host_Error (char *error, ...);
void Host_EndGame (char *message, ...);
void Host_Frame (float time);
void Host_Quit_f (void);
void Host_ClientCommands (char *fmt, ...);
void Host_ShutdownServer (qboolean crash);

extern qboolean		msg_suppress_1;		// suppresses resolution and cache size console output
										//  an fullscreen DIB focus gain/loss

extern	unsigned int			defLosses;	// Defenders losses in Siege
extern	unsigned int			attLosses;	// Attackers Losses in Siege

extern int			cl_keyholder;
extern int			cl_doc;
