#!/bin/sh

if test "`uname`" = "FreeBSD" ; then
	MAKE=gmake
else
	MAKE=make
fi

echo "Building hcc, the HexenC compiler.."
$MAKE -C hcc
echo "" && echo "Now building qfiles.."
$MAKE -C qfiles
echo "" && echo "Now building genmodel.."
$MAKE -C genmodel
echo "" && echo "Now building light, vis and qbsp.."
$MAKE -C utils
