DEBUG=no

BINARY=hwmaster.exe

MINGWDIR=/mingw
CC = gcc
LINKER = $(CC)

ifeq "$(DEBUG)" "yes"
CFLAGS = -I. -I$(MINGWDIR)/include -DDEBUG_BUILD -g -Wall
else
CFLAGS = -I. -I$(MINGWDIR)/include -O2 -march=i586 -Wall
endif

LDFLAGS = -L$(MINGWDIR)/lib -lm -lwsock32 -lwinmm -mconsole

%.o: %.c
	$(CC) -c $(CFLAGS) -o $@ $<

MASTEROBJS = cmds.o net_test.o net.o

all: $(BINARY) 

$(BINARY) : $(MASTEROBJS)
	$(LINKER) -o $(BINARY) $(MASTEROBJS) $(LDFLAGS)
	
clean:
	rm -f $(MASTEROBJS) core

