#!/bin/sh

os=`uname -s`

if [[ ! -f loki_patch.$os ]]; then
	echo ""
	echo "A loki_patch binary for your $os operating system cannot"
	echo "be found. Please compile one from the sources and rename"
	echo "to loki_patch.$os for this script to use it. Exitting..."
	echo ""
	exit 1
fi

echo ""
echo "=============================================================="
echo "This will patch Hexen2 PAK files (cdrom-1.03 version) to 1.11,"
echo "which is a required update by Raven/Activision."
echo -n "Would you like to apply this update? [Y/n]: "
read answer
case $answer in
   [Nn]*)
       ;;
   *)
       ./loki_patch.$os h2_103_111.dat .
   ;;
esac

echo "                "
