
MINGWDIR=/mingw

CC = gcc
LINKER = $(CC)
BINARY=dhcc.exe
DESTDIR= ./bin
CFLAGS = -O2 -Wall -I$(MINGWDIR)/include
LDFLAGS = -mconsole
LDLIBS= 

all : $(BINARY)

clean : 
	rm -f *.o core

# Rules for turning source files into .o files
%.o: %.c
	$(CC) -c $(CFLAGS) -o $@ $<

DHCCOBJS= cmdlib.o \
	pr_comp.o \
	pr_lex.o \
	dcc.o \
	hcc.o

$(BINARY) : $(DHCCOBJS)
	$(LINKER) -o $(DESTDIR)/$(BINARY) $(DHCCOBJS) $(LDFLAGS) $(LDLIBS)
