#!/bin/sh

EXE_EXT=
BIN_FILES="dcc/bin/dhcc h2_utils/bin/hcc h2mp_utils/bin/hcc 
jsh2color/jsh2colour
h2_utils/bin/vis h2_utils/bin/qbsp h2_utils/bin/light 
h2mp_utils/bin/vis h2_utils/bin/qbsp h2_utils/bin/light 
h2mp_utils/bin/qfiles h2mp_utils/bin/genmodel"

if env | grep -i windir > __tmp.tmp; then
EXE_EXT=".exe";
fi
rm -f __tmp.tmp

if test "`uname`" = "FreeBSD" ; then
	MAKE=gmake
else
	MAKE=make
fi

if [ "$1" = "strip" ]
then
	for i in ${BIN_FILES}
	do
	    strip ${i}${EXE_EXT}
	done
exit 0
fi

if [ "$1" = "clean" ]
then
make -s -C h2mp_utils/hcc clean
make -s -C h2_utils/hcc clean
make -s -C h2mp_utils/qfiles clean
make -s -C h2mp_utils/genmodel clean
make -s -C h2mp_utils/utils clean
make -s -C h2_utils/utils clean
make -s -C dcc clean
make -s -C jsh2color clean
exit 0
fi

echo "Building hcc, the HexenC compiler.."
$MAKE -C h2mp_utils/hcc
echo "" && echo "Now building hcc, old version"
$MAKE -C h2_utils/hcc
echo "" && echo "Now building qfiles.."
$MAKE -C h2mp_utils/qfiles
echo "" && echo "Now building genmodel.."
$MAKE -C h2mp_utils/genmodel
echo "" && echo "Now building light, vis and qbsp.."
$MAKE -C h2mp_utils/utils
echo "" && echo "Now building light, vis and qbsp, old versions.."
$MAKE -C h2_utils/utils
echo "" && echo "Now building dhcc, a progs.dat decompiler.."
$MAKE -C dcc
echo "" && echo "Now building jsh2colour, a lit file generator.."
$MAKE -C jsh2color

