#!/bin/sh

echo "Building hcc, the HexenC compiler.."
make -C h2mp_utils/hcc -f Makefile.mingw
echo "" && echo "Now building hcc, old version"
make -C h2_utils/hcc -f Makefile.mingw
echo "" && echo "Now building qfiles.."
make -C h2mp_utils/qfiles -f Makefile.mingw
echo "" && echo "Now building genmodel.."
make -C h2mp_utils/genmodel -f Makefile.mingw
echo "" && echo "Now building light, vis and qbsp.."
make -C h2mp_utils/utils -f Makefile.mingw
echo "" && echo "Now building light, vis and qbsp, old versions.."
make -C h2_utils/utils -f Makefile.mingw
echo "" && echo "Now building dhcc, a progs.dat decompiler.."
make -C dcc -f Makefile.mingw

