#!/bin/sh

if test "`uname`" = "FreeBSD" ; then
	MAKE=gmake
else
	MAKE=make
fi

$MAKE -C h2mp_utils/hcc clean
$MAKE -C h2_utils/hcc clean
$MAKE -C h2mp_utils/qfiles clean
$MAKE -C h2mp_utils/genmodel clean
$MAKE -C h2mp_utils/utils clean
$MAKE -C h2_utils/utils clean
$MAKE -C dcc clean

