#!/bin/sh

if [ -f /usr/local/bin/make ]; then
	MAKE=/usr/local/bin/make
elif [ -f /usr/bin/make ]; then
	MAKE=/usr/bin/make
elif [ -f /usr/local/bin/gmake ]; then
	MAKE=/usr/local/bin/gmake
elif [ -f /usr/bin/gmake ]; then
	MAKE=/usr/bin/gmake
else
	echo "Error: make or gmake not found"
	exit 1
fi

$MAKE -C h2mp_utils/hcc clean
$MAKE -C h2_utils/hcc clean
$MAKE -C h2mp_utils/qfiles clean
$MAKE -C h2mp_utils/genmodel clean
$MAKE -C h2mp_utils/utils clean
$MAKE -C h2_utils/utils clean
$MAKE -C dcc clean

