#!/bin/sh

make -C h2mp_utils/hcc -f Makefile.mingw clean
make -C h2_utils/hcc -f Makefile.mingw clean
make -C h2mp_utils/qfiles -f Makefile.mingw clean
make -C h2mp_utils/genmodel -f Makefile.mingw clean
make -C h2mp_utils/utils -f Makefile.mingw clean
make -C h2_utils/utils -f Makefile.mingw clean
make -C dcc -f Makefile.mingw clean

